from .views import *
from django.urls import path

app_name = 'gest'


urlpatterns = [
    
    path('', login, name='login'),
    path('dashboard', dashboard, name='dashboard'),
    path('produits', produits, name='produits'),
    path('json', prodliste, name='json'),
    path('add_prod', add_produits, name='add_produits'),
    path('category', category, name='category'),
    path('ventes', ventes, name='ventes'),
    path('ven_form', add_ventes, name='ven_form'),
    path('clients', clients, name='clients'),
    path('cltprofil/<str:pk>', clt_profil, name='cltprofil' ),
    path('cltprofilfiltred/<str:pk>', clt_profil, name='cltprofilfiltred' ),
    path('rester/<str:pk>', rester, name='rester'),
    path('supp_clt/<str:pk>', supp_clt, name='supp_clt'),
    path('frs', frs, name='frs'),
    path('frsprofil/<str:pk>', frs_profil, name='frsprofil'),
    path('payer/<str:pk>', payer, name='payer'),
    path('impayer/<str:pk>', impayer, name='impayer'),
    path('frs_supp/<str:pk>', frs_supp, name='frs_supp'),
    path('factureUpdate/<str:pk>', factureUpdate, name='factureUpdate'),
    path('devisUpdate/<str:pk>', devisUpdate, name='devisUpdate'),
    path('category_delete/<str:pk>', delete_category, name='category_delete'),
    path('panier', panier, name='panier'),
    path('panier_vider', panier_vider, name='panier_vider'),
    path('vente_annul/<str:pk>', delete_vente, name='vente_annul'),
    path('validation/<str:client>/<str:mode>', validation, name='validation'),
    path('annul', annul, name='annul'),
    path('dele/<str:pk>', panier_an, name='dele'),
    path('edit/<str:pk>', productEditor, name='edit'),
    path('clientEditor/<str:pk>', clientEditor, name='clientEditor'),
    path('deleteProd/<str:pk>', deleteProduct, name='deleteProd'),
    path('facsupp/<str:pk>', facsupp, name='facsupp'),
    path('devsupp/<str:pk>', devsupp, name='devsupp'),
    path('journal/<str:dateone>/<str:datetwo>', journal, name='journal'),
    path('product_panier/<str:pk>/<str:remise>/<str:qte>/<str:pph>', ajouter_panier, name='product_panier'),
    path('factureOrderAdd/<str:pk>', factureOrderAdd, name='factureOrderAdd'),
    path('devisProdAdd/<str:pk>', devisProdAdd, name='devisProdAdd'),
    path('choicespdfbl/<str:idFacture>', choicespdfbl, name='choicespdfbl'),
    path('facture', facture, name='facture'),
    path('paiments', paiments, name='paiments'),
    path('delete_paiments/<str:pk>', delete_paiments, name='delete_paiments'),
    path('devis', devis, name='devis'),
    path('pdf/<str:idFacture>', pdfFacture, name='pdf'),
    path('devispdf/<str:idFacture>', pdfDevis, name='devispdf'),
    path('bl/<str:idFacture>', pdfBon, name='bl'),
    path('im/<str:pk>', im, name='im'),
    path('pa/<str:pk>', pa, name='pa'),
    path('imvente/<str:pk>', imvente, name='imvente'),
    path('pavente/<str:pk>', pavente, name='pavente'),
    path('remisedata/<str:name>', remiseData, name='remisedata'),
    path('backupme', backupfile, name="backupme"),
    path('logout', logoutPage, name="logout"),
]