# Generated by Django 2.2 on 2021-07-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=9000, null=True)),
                ('remise', models.IntegerField(blank=True, default=0, null=True)),
                ('quantite', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9000)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('date_expire', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('codeBarre', models.CharField(blank=True, max_length=9000, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=9000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest.Product')),
            ],
        ),
    ]
