# Generated by Django 3.1.7 on 2022-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest', '0003_auto_20220630_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tva_order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
