# Generated by Django 3.1.7 on 2022-08-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest', '0004_order_tva_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bl', models.IntegerField(blank=True, null=True)),
                ('total_facture', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
