# Generated by Django 3.1.7 on 2022-08-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest', '0005_numerateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='article',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='article_prix',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='article_quantite',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='article_remise',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='article_total',
        ),
        migrations.RemoveField(
            model_name='prod',
            name='devis',
        ),
        migrations.AddField(
            model_name='prod',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gest.devis'),
        ),
        migrations.AddField(
            model_name='prod',
            name='nom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='gest.product'),
        ),
        migrations.AddField(
            model_name='prod',
            name='p_remise',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='p_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='quantite',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='remise',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='tva_order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
