# Generated by Django 3.1.7 on 2022-09-12 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gest', '0007_auto_20220912_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gest.client'),
        ),
        migrations.AlterField(
            model_name='paiment',
            name='commande_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gest.facture'),
        ),
    ]
